<?php

namespace App\Services;

class BenchmarkDataset
{
    /**
     * Mengembalikan 40 skenario prompt benchmark baku untuk evaluasi jurnal.
     * Mencakup 6 kategori, atribut filter (harga, operasional, 24 jam),
     * spasial (dalam & luar Padang, wilayah), entitas informal/legenda,
     * multi-turn, sapaan, dan out-of-scope query.
     *
     * @return array<int, array<string, mixed>>
     */
    public static function getDataset(): array
    {
        return [
            // ===== 1. KATEGORI PANTAI (1-5) =====
            [
                'id' => 1,
                'grup' => 'Kategori - Pantai Eksplisit',
                'prompt' => 'Rekomendasikan pantai yang bagus di Padang',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => 'Pantai',
                'expected_nama' => null,
                'expected_filters' => [],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],
            [
                'id' => 2,
                'grup' => 'Kategori - Pantai Implisit',
                'prompt' => 'Mau main pasir dan lihat ombak laut di Padang',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => 'Pantai',
                'expected_nama' => null,
                'expected_filters' => [],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],
            [
                'id' => 3,
                'grup' => 'Kategori - Pantai Terdekat',
                'prompt' => 'Pantai yang paling dekat dari lokasi saya',
                'lat' => '-0.9489',
                'lng' => '100.3572',
                'riwayat' => [],
                'expected_kategori' => 'Pantai',
                'expected_nama' => null,
                'expected_filters' => ['urutan' => 'terdekat'],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],
            [
                'id' => 4,
                'grup' => 'Kategori - Pantai Kata Kunci',
                'prompt' => 'Pantai pasir putih yang pemandangannya indah',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => 'Pantai',
                'expected_nama' => null,
                'expected_filters' => ['kata_kunci' => 'pasir putih'],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],
            [
                'id' => 5,
                'grup' => 'Kategori - Pantai Ramah Anak',
                'prompt' => 'Pantai yang ombaknya tenang dan cocok untuk anak-anak',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => 'Pantai',
                'expected_nama' => null,
                'expected_filters' => [],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],

            // ===== 2. KATEGORI PULAU (6-8) =====
            [
                'id' => 6,
                'grup' => 'Kategori - Pulau Snorkeling',
                'prompt' => 'Pulau di Padang yang bagus untuk snorkeling dan diving',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => 'Pulau',
                'expected_nama' => null,
                'expected_filters' => [],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],
            [
                'id' => 7,
                'grup' => 'Kategori - Pulau Resort',
                'prompt' => 'Rekomendasikan pulau resort terbaik dengan vila di Padang',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => 'Pulau',
                'expected_nama' => null,
                'expected_filters' => [],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],
            [
                'id' => 8,
                'grup' => 'Kategori - Pulau Karang',
                'prompt' => 'Pulau karang kecil yang lautnya jernih',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => 'Pulau',
                'expected_nama' => null,
                'expected_filters' => [],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],

            // ===== 3. KATEGORI ALAM (9-12) =====
            [
                'id' => 9,
                'grup' => 'Kategori - Alam Air Terjun',
                'prompt' => 'Wisata air terjun alami di Padang yang sejuk',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => 'Alam',
                'expected_nama' => null,
                'expected_filters' => [],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],
            [
                'id' => 10,
                'grup' => 'Kategori - Alam Pemandangan Bukit',
                'prompt' => 'Spot sunset pemandangan kota Padang dari atas bukit',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => 'Alam',
                'expected_nama' => null,
                'expected_filters' => [],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],
            [
                'id' => 11,
                'grup' => 'Kategori - Alam Hutan Lindung',
                'prompt' => 'Taman konservasi hutan atau kebun raya di Padang',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => 'Alam',
                'expected_nama' => null,
                'expected_filters' => [],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],
            [
                'id' => 12,
                'grup' => 'Kategori - Alam Bukit Santai',
                'prompt' => 'Bukit santai dengan pemandangan laut yang cocok untuk keluarga',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => 'Alam',
                'expected_nama' => null,
                'expected_filters' => [],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],

            // ===== 4. KATEGORI MUSEUM (13-15) =====
            [
                'id' => 13,
                'grup' => 'Kategori - Museum Budaya',
                'prompt' => 'Museum budaya Minangkabau di Kota Padang',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => 'Museum',
                'expected_nama' => null,
                'expected_filters' => [],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],
            [
                'id' => 14,
                'grup' => 'Kategori - Museum Rumah Gadang',
                'prompt' => 'Museum arsitektur rumah gadang dan artefak sejarah',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => 'Museum',
                'expected_nama' => null,
                'expected_filters' => [],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],
            [
                'id' => 15,
                'grup' => 'Kategori - Museum Kolonial',
                'prompt' => 'Museum peninggalan kolonial atau kota tua di Padang',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => 'Museum',
                'expected_nama' => null,
                'expected_filters' => [],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],

            // ===== 5. KATEGORI SEJARAH (16-18) =====
            [
                'id' => 16,
                'grup' => 'Kategori - Sejarah Landmark',
                'prompt' => 'Jembatan Siti Nurbaya buka jam berapa dan ada apa saja?',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => 'Sejarah',
                'expected_nama' => 'Jembatan Siti Nurbaya',
                'expected_filters' => [],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],
            [
                'id' => 17,
                'grup' => 'Kategori - Sejarah Religi',
                'prompt' => 'Masjid bersejarah tertua peninggalan abad ke-19 di Padang',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => 'Sejarah',
                'expected_nama' => null,
                'expected_filters' => [],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],
            [
                'id' => 18,
                'grup' => 'Kategori - Sejarah Monumen',
                'prompt' => 'Tugu peringatan bersejarah di Padang',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => 'Sejarah',
                'expected_nama' => null,
                'expected_filters' => [],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],

            // ===== 6. KATEGORI KULINER (19-22) =====
            [
                'id' => 19,
                'grup' => 'Kategori - Kuliner Rendang',
                'prompt' => 'Tempat makan rendang khas Padang yang paling terkenal',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => 'Kuliner',
                'expected_nama' => null,
                'expected_filters' => [],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],
            [
                'id' => 20,
                'grup' => 'Kategori - Kuliner Soto',
                'prompt' => 'Warung soto padang kuah kaldu sapi gurih',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => 'Kuliner',
                'expected_nama' => null,
                'expected_filters' => [],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],
            [
                'id' => 21,
                'grup' => 'Kategori - Kuliner Mie',
                'prompt' => 'Tempat makan mie kocok kaldu sapi di Padang',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => 'Kuliner',
                'expected_nama' => null,
                'expected_filters' => [],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],
            [
                'id' => 22,
                'grup' => 'Kategori - Kuliner Oleh-oleh',
                'prompt' => 'Pasar atau pusat beli oleh-oleh khas Padang',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => 'Kuliner',
                'expected_nama' => null,
                'expected_filters' => [],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],

            // ===== 7. ATRIBUT FILTER (23-28) =====
            [
                'id' => 23,
                'grup' => 'Filter - Tiket Gratis',
                'prompt' => 'Wisata gratis di Padang tanpa bayar tiket masuk',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => null,
                'expected_nama' => null,
                'expected_filters' => ['gratis' => true],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],
            [
                'id' => 24,
                'grup' => 'Filter - Batas Harga',
                'prompt' => 'Tempat wisata yang harga tiketnya di bawah 10000 rupiah',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => null,
                'expected_nama' => null,
                'expected_filters' => ['max_harga' => 10000],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],
            [
                'id' => 25,
                'grup' => 'Filter - Buka 24 Jam',
                'prompt' => 'Tempat makan atau restoran yang buka 24 jam di Padang',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => 'Kuliner',
                'expected_nama' => null,
                'expected_filters' => ['buka_24_jam' => true],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],
            [
                'id' => 26,
                'grup' => 'Filter - Jam Sekarang',
                'prompt' => 'Wisata apa saja yang buka sekarang jam segini?',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => null,
                'expected_nama' => null,
                'expected_filters' => ['jam_sekarang' => true],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],
            [
                'id' => 27,
                'grup' => 'Filter - Urutan Termurah',
                'prompt' => 'Wisata pantai termurah atau paling hemat di Padang',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => 'Pantai',
                'expected_nama' => null,
                'expected_filters' => ['urutan' => 'termurah'],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],
            [
                'id' => 28,
                'grup' => 'Filter - Urutan Terbaik',
                'prompt' => 'Tempat wisata dengan rating terbaik dan paling direkomendasikan',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => null,
                'expected_nama' => null,
                'expected_filters' => ['urutan' => 'terbaik'],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],

            // ===== 8. FILTER SPASIAL & WILAYAH (29-31) =====
            [
                'id' => 29,
                'grup' => 'Spasial - Wilayah Bungus',
                'prompt' => 'Pantai di daerah Bungus Teluk Kabung',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => 'Pantai',
                'expected_nama' => null,
                'expected_filters' => ['wilayah' => 'Bungus'],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],
            [
                'id' => 30,
                'grup' => 'Spasial - Wilayah Padang Barat',
                'prompt' => 'Tempat makan dan nongkrong di Padang Barat',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => 'Kuliner',
                'expected_nama' => null,
                'expected_filters' => ['wilayah' => 'Padang Barat'],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],
            [
                'id' => 31,
                'grup' => 'Spasial - Wilayah Padang Selatan',
                'prompt' => 'Wisata di kecamatan Padang Selatan',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => null,
                'expected_nama' => null,
                'expected_filters' => ['wilayah' => 'Padang Selatan'],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],

            // ===== 9. ENTITAS INFORMAL & FALLBACK LEGENDA (32-34) =====
            [
                'id' => 32,
                'grup' => 'Entitas - Pantai Malin Kundang',
                'prompt' => 'Pantai Malin Kundang',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => 'Pantai',
                'expected_nama' => 'Pantai Air Manis',
                'expected_filters' => [],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],
            [
                'id' => 33,
                'grup' => 'Entitas - Batu Malin Kundang',
                'prompt' => 'Batu Malin Kundang lokasinya di mana dan berapa tiketnya?',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => null,
                'expected_nama' => 'Pantai Air Manis',
                'expected_filters' => [],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],
            [
                'id' => 34,
                'grup' => 'Entitas - Hutan Bung Hatta',
                'prompt' => 'Taman Hutan Bung Hatta buka sampai jam berapa?',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => 'Alam',
                'expected_nama' => 'Taman Hutan Raya Bung Hatta',
                'expected_filters' => [],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],

            // ===== 10. LOKASI LUAR KOTA PADANG (35) =====
            [
                'id' => 35,
                'grup' => 'Spasial - User di Luar Padang',
                'prompt' => 'Rekomendasi wisata pantai terbaik untuk liburan saya',
                'lat' => '-6.200000',
                'lng' => '106.816666', // Jakarta (>900 km)
                'riwayat' => [],
                'expected_kategori' => 'Pantai',
                'expected_nama' => null,
                'expected_filters' => [],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],

            // ===== 11. MULTI-TURN CONTEXT (36) =====
            [
                'id' => 36,
                'grup' => 'Multi-turn - Rujukan Entitas',
                'prompt' => 'Berapa harga tiket yang pertama?',
                'lat' => null,
                'lng' => null,
                'riwayat' => [
                    ['role' => 'user', 'pesan' => 'Rekomendasikan museum di Padang'],
                    ['role' => 'assistant', 'pesan' => 'Berikut rekomendasinya: 1. **Museum Adityawarman** 2. **Museum Situs Rumah Bersejarah** 3. **Rumah Gadang Pallindo**'],
                ],
                'expected_kategori' => 'Museum',
                'expected_nama' => 'Museum Adityawarman',
                'expected_filters' => [],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],

            // ===== 12. SAPAAN & CHIT-CHAT (37-38) =====
            [
                'id' => 37,
                'grup' => 'Chit-chat - Sapaan',
                'prompt' => 'Halo selamat pagi min',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => null,
                'expected_nama' => null,
                'expected_filters' => [],
                'is_sapaan' => true,
                'expect_empty' => true,
            ],
            [
                'id' => 38,
                'grup' => 'Chit-chat - Terima Kasih',
                'prompt' => 'Terima kasih banyak atas infonya ya!',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => null,
                'expected_nama' => null,
                'expected_filters' => [],
                'is_sapaan' => false,
                'expect_empty' => false,
            ],

            // ===== 13. OUT-OF-SCOPE / DATA TIDAK TERSEDIA (39-40) =====
            [
                'id' => 39,
                'grup' => 'Out-of-Scope - Wisata Salju',
                'prompt' => 'Rekomendasi tempat main salju dan ski es di Padang',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => null,
                'expected_nama' => null,
                'expected_filters' => [],
                'is_sapaan' => false,
                'expect_empty' => true, // Harap jujur tidak ada data
            ],
            [
                'id' => 40,
                'grup' => 'Out-of-Scope - Candi Hindu',
                'prompt' => 'Wisata candi peninggalan kerajaan Hindu di Kota Padang',
                'lat' => null,
                'lng' => null,
                'riwayat' => [],
                'expected_kategori' => 'Sejarah',
                'expected_nama' => null,
                'expected_filters' => [],
                'is_sapaan' => false,
                'expect_empty' => true, // Harap jujur tidak ada data
            ],
        ];
    }
}
