#!/usr/bin/env python3
import os
import re
import subprocess
import sys

JURNAL_DIR = "/var/www/html/JIS/jurnal"

ACADEMIC_CSS = """
@page {
    size: A4;
    margin: 3cm 2.5cm 2.5cm 3cm;
    @bottom-right {
        content: counter(page);
        font-family: "Times New Roman", "Liberation Serif", serif;
        font-size: 10pt;
    }
}

@page:first {
    @bottom-right {
        content: "";
    }
}

body {
    font-family: "Times New Roman", "Liberation Serif", Times, serif;
    font-size: 12pt;
    line-height: 1.6;
    color: #111;
    background-color: #fff;
    text-align: justify;
    text-justify: inter-word;
    margin: 0;
    padding: 0;
}

/* Hide redundant title-block-header generated by Pandoc metadata */
header#title-block-header,
.title-block-header,
h1.title {
    display: none !important;
}

h1 {
    font-size: 16pt;
    font-weight: bold;
    text-align: center;
    margin-top: 1.5em;
    margin-bottom: 0.8em;
    line-height: 1.3;
    page-break-before: always;
    break-before: page;
}

/* First visible H1 doesn't need page break */
h1:first-of-type,
body > h1:first-child,
body > div > h1:first-child {
    page-break-before: avoid !important;
    break-before: avoid !important;
    margin-top: 0 !important;
}

/* Subtitle under first H1 */
h1 + p {
    text-align: center !important;
    text-indent: 0 !important;
    font-size: 11pt !important;
    font-style: italic;
    color: #444;
    margin-top: -0.4em;
    margin-bottom: 1.5em;
}

h2 {
    font-size: 14pt;
    font-weight: bold;
    margin-top: 1.4em;
    margin-bottom: 0.6em;
    page-break-after: avoid;
    break-after: avoid;
}

/* Page breaks for major chapters and prelims in Thesis */
h2[id^="bab-"], 
h2[id^="lembar-"],
h2[id^="pernyataan-"],
h2[id^="kata-pengantar"],
h2[id^="daftar-"] {
    page-break-before: always;
    break-before: page;
}

h3 {
    font-size: 12pt;
    font-weight: bold;
    margin-top: 1.2em;
    margin-bottom: 0.4em;
    page-break-after: avoid;
    break-after: avoid;
}

h4 {
    font-size: 12pt;
    font-weight: bold;
    font-style: italic;
    margin-top: 1em;
    margin-bottom: 0.3em;
    page-break-after: avoid;
    break-after: avoid;
}

p {
    margin-top: 0;
    margin-bottom: 0.8em;
    text-indent: 1cm;
    text-align: justify;
    text-justify: inter-word;
}

/* No indent for headings, lists, tables, captions, abstracts */
h1 + p, h2 + p, h3 + p, h4 + p,
.no-indent,
blockquote p,
table p,
ul p, ol p,
div.center p,
.caption,
.abstract-text,
.keywords-text {
    text-indent: 0 !important;
}

/* =======================================================
   FORMATTING KHUSUS ABSTRAK (RATA KIRI-KANAN / JUSTIFIED)
   ======================================================= */
.abstract-container {
    margin: 1.8em 0;
}

.abstract-container {
    margin: 1.2em 0 1.8em 0;
}

.abstract-container h2,
.abstract-container h3,
h2[id*="abstrak"], h2[id*="abstract"],
h3[id*="abstrak"], h3[id*="abstract"],
#abstrak, #abstract {
    text-align: center !important;
    font-size: 11pt !important;
    font-weight: bold !important;
    text-transform: uppercase;
    letter-spacing: 1.2px;
    margin-top: 1.2em !important;
    margin-bottom: 0.6em !important;
    page-break-after: avoid;
    break-after: avoid;
}

.abstract-container p,
.abstract-text,
p.abstract-text,
h2[id*="abstrak"] + p, h2[id*="abstract"] + p,
h3[id*="abstrak"] + p, h3[id*="abstract"] + p {
    text-align: justify !important;
    text-justify: inter-word !important;
    text-indent: 0 !important;
    font-size: 10pt !important;
    line-height: 1.45 !important;
    margin-left: 1.2cm !important;
    margin-right: 1.2cm !important;
    margin-bottom: 0.6em !important;
}

.abstract-container p.keywords-text,
p.keywords-text,
.abstract-container p:last-of-type {
    text-align: justify !important;
    text-justify: inter-word !important;
    text-indent: 0 !important;
    font-size: 10pt !important;
    line-height: 1.4 !important;
    margin-left: 1.2cm !important;
    margin-right: 1.2cm !important;
    margin-top: 0.7em !important;
    margin-bottom: 1.8em !important;
}

hr {
    border: 0;
    border-top: 1px solid #ccc;
    margin: 2em 0;
}

table {
    border-collapse: collapse;
    width: 100% !important;
    max-width: 100% !important;
    box-sizing: border-box !important;
    margin: 1.2em 0 1.6em 0;
    font-size: 8.5pt !important;
    line-height: 1.35;
    page-break-inside: auto;
}

thead {
    display: table-header-group;
}

tr {
    page-break-inside: avoid;
    break-inside: avoid;
}

th {
    background-color: #f3f4f6;
    border: 1px solid #333;
    padding: 5px 6px !important;
    font-weight: bold;
    text-align: left;
    font-size: 8.5pt !important;
    word-break: break-word;
    overflow-wrap: break-word;
}

td {
    border: 1px solid #555;
    padding: 4px 6px !important;
    vertical-align: top;
    font-size: 8.5pt !important;
    word-break: break-word;
    overflow-wrap: break-word;
}

tr:nth-child(even) td {
    background-color: #fafbfc;
}

img {
    max-width: 92%;
    height: auto;
    display: block;
    margin: 14px auto 6px auto;
    border: 1px solid #ddd;
    border-radius: 4px;
    box-shadow: 0 1px 4px rgba(0,0,0,0.1);
    page-break-inside: avoid;
    break-inside: avoid;
}

/* Captions - HANYA untuk keterangan gambar/tabel */
p.caption,
.caption,
figcaption {
    text-align: center !important;
    text-indent: 0 !important;
    font-size: 10pt !important;
    font-style: italic;
    color: #333;
    margin-top: 6px;
    margin-bottom: 1.4em;
}

em {
    font-style: italic;
}

pre, code {
    font-family: "Courier New", Courier, monospace;
    font-size: 9pt;
}

pre {
    background-color: #f8f9fa;
    border: 1px solid #e2e8f0;
    border-radius: 5px;
    padding: 10px 14px;
    overflow-x: auto;
    line-height: 1.35;
    margin: 1.2em 0;
    page-break-inside: avoid;
    break-inside: avoid;
}

code {
    background-color: #edf2f7;
    padding: 1px 4px;
    border-radius: 3px;
}

pre code {
    background-color: transparent;
    padding: 0;
    border-radius: 0;
}

blockquote {
    border-left: 4px solid #1a56db;
    margin: 1em 0 1em 1cm;
    padding: 0.5em 1em;
    background-color: #f8fafc;
    color: #334155;
    font-style: italic;
    page-break-inside: avoid;
    break-inside: avoid;
}

ul, ol {
    margin-top: 0.4em;
    margin-bottom: 0.8em;
    padding-left: 2cm;
}

li {
    margin-bottom: 0.3em;
}

.math {
    font-family: "Cambria Math", "Times New Roman", serif;
}
"""

def convert_md_to_pdf(md_filename, pdf_filename, is_journal=False):
    md_path = os.path.join(JURNAL_DIR, md_filename)
    html_path = os.path.join(JURNAL_DIR, md_filename.replace(".md", ".html"))
    pdf_path = os.path.join(JURNAL_DIR, pdf_filename)

    print(f"[*] Processing {md_filename} -> {pdf_filename}...")

    # Step 1: Pandoc MD to HTML
    cmd_pandoc = [
        "pandoc",
        md_path,
        "-s",
        "--mathjax",
        "--metadata", "title=",
        "-o", html_path
    ]
    res_pandoc = subprocess.run(cmd_pandoc, capture_output=True, text=True, cwd=JURNAL_DIR)
    if res_pandoc.returncode != 0:
        print(f"[!] Pandoc error on {md_filename}: {res_pandoc.stderr}")
        return False

    # Step 2: Inject Custom Academic CSS & Tag Abstracts/Captions
    with open(html_path, "r", encoding="utf-8") as f:
        html_content = f.read()

    # Clear title tag so Chrome never shows it in print headers
    html_content = re.sub(r'<title>.*?</title>', '<title></title>', html_content, flags=re.DOTALL)

    # 1. Tag caption paragraphs
    html_content = re.sub(
        r'<p>(<em>(?:Gambar|Figure|Tabel|Table)\s*\d+[^<]*</em>)</p>',
        r'<p class="caption">\1</p>',
        html_content
    )

    # 2. Tag abstract headings and their paragraphs
    pattern_abstrak = re.compile(
        r'(<h[23][^>]*id=["\'](?:abstrak|abstract)["\'][^>]*>.*?</h[23]>)\s*'
        r'((?:<p>.*?</p>\s*)+?)'
        r'(<p>(?:<strong>(?:Kata Kunci|Keywords):?</strong>|<em>(?:Kata Kunci|Keywords):?</em>).*?</p>)',
        re.DOTALL | re.IGNORECASE
    )

    def replace_abstrak(match):
        heading = match.group(1)
        p_body = match.group(2)
        p_keywords = match.group(3)
        p_body = re.sub(r'<p>', '<p class="abstract-text">', p_body, flags=re.IGNORECASE)
        p_keywords = re.sub(r'<p>', '<p class="keywords-text">', p_keywords, flags=re.IGNORECASE)
        return f'<div class="abstract-container">\n{heading}\n{p_body}\n{p_keywords}\n</div>'

    html_content = pattern_abstrak.sub(replace_abstrak, html_content)

    custom_style_block = f"<style>\n{ACADEMIC_CSS}\n</style>"
    if "</head>" in html_content:
        html_content = html_content.replace("</head>", f"{custom_style_block}\n</head>")
    else:
        html_content = f"{custom_style_block}\n{html_content}"

    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html_content)

    # Step 3: Chrome Headless HTML to PDF
    import tempfile
    with tempfile.TemporaryDirectory() as temp_profile_dir:
        cmd_chrome = [
            "google-chrome",
            "--headless",
            "--disable-gpu",
            "--no-sandbox",
            "--disable-dev-shm-usage",
            "--no-pdf-header-footer",
            f"--user-data-dir={temp_profile_dir}",
            f"--print-to-pdf={pdf_path}",
            html_path
        ]
        try:
            res_chrome = subprocess.run(cmd_chrome, capture_output=True, text=True, cwd=JURNAL_DIR, timeout=45)
            if res_chrome.returncode != 0:
                print(f"[!] Chrome error on {md_filename}: {res_chrome.stderr}")
                return False
        except subprocess.TimeoutExpired:
            print(f"[!] Chrome rendering timed out on {md_filename}")
            return False

    # Step 4: Pandoc MD to DOCX
    docx_path = os.path.join(JURNAL_DIR, md_filename.replace(".md", ".docx"))
    cmd_docx = ["pandoc", md_path, "-o", docx_path]
    subprocess.run(cmd_docx, capture_output=True, text=True, cwd=JURNAL_DIR)

    if os.path.exists(pdf_path):
        size_mb = os.path.getsize(pdf_path) / (1024 * 1024)
        print(f"[✓] Successfully generated: {pdf_path} ({size_mb:.2f} MB)")
        if os.path.exists(docx_path):
            size_docx_mb = os.path.getsize(docx_path) / (1024 * 1024)
            print(f"[✓] Successfully generated: {docx_path} ({size_docx_mb:.2f} MB)")
        return True
    else:
        print(f"[!] PDF not found: {pdf_path}")
        return False

def main():
    # If a specific file is requested via CLI argument, only compile that file (lightning fast)
    if len(sys.argv) > 1:
        target = os.path.basename(sys.argv[1])
        pdf_name = target.replace(".md", ".pdf")
        is_journal = "JURNAL" in target.upper()
        if os.path.exists(os.path.join(JURNAL_DIR, target)):
            convert_md_to_pdf(target, pdf_name, is_journal)
            return
        else:
            print(f"[!] Target file not found: {target}")
            return

    files_to_convert = [
        ("DRAFT_JURNAL_ILMIAH_INDONESIA.md", "DRAFT_JURNAL_ILMIAH_INDONESIA.pdf", True),
        ("DRAFT_JURNAL_IJG_ENGLISH.md", "DRAFT_JURNAL_IJG_ENGLISH.pdf", True),
        ("DRAFT_TESIS_LENGKAP.md", "DRAFT_TESIS_LENGKAP.pdf", False),
    ]

    success_count = 0
    for md_file, pdf_file, is_journal in files_to_convert:
        if os.path.exists(os.path.join(JURNAL_DIR, md_file)):
            if convert_md_to_pdf(md_file, pdf_file, is_journal):
                success_count += 1
        else:
            print(f"[!] File not found: {md_file}")

    print(f"\n[DONE] {success_count}/{len(files_to_convert)} PDF files successfully compiled.")

if __name__ == "__main__":
    main()
